import sahnesen from "../assets/images/sahnesen.webp";
import iphonechip from "../assets/images/iphonechip.webp";
import gray from "../assets/images/gray.webp";
import runaley2 from "../assets/images/runaley2.webp";
import itstime from "../assets/images/itstime.webp";
import homework2 from "../assets/images/homework3.webp";
import projectbanner from "../assets/images/projectbanner.webp";
import blogbanner from "../assets/images/blogbanner.webp";
import kutukalan from "../assets/logo/kutukalan.png";
import sabirotologo from "../assets/logo/sabirotologo.png";
import dockerpostman from "../assets/images/docker&postman.webp";
import sunucu from "../assets/images/sunucu.webp";
import sabiroto from "../assets/images/sabiroto.webp";
import poppin from "../assets/images/poppin.webp";
import garanticard from "../assets/images/garanticard.webp";
import logo from "../assets/logo/logo.png";
import logo2 from "../assets/logo/logo2.png";
import navbarlogo from "../assets/logo/navbarlogo.png";
import createMusicImg from "../assets/images/createMusicImg.webp";
import readmeImg from "../assets/images/readmeImg.webp";

import manrunning3 from "../assets/images/manrunning3.webp";
export { manrunning3 };

import notly2 from "../assets/images/desktopappImages/notly2.webp";
import notly3 from "../assets/images/desktopappImages/notly3.webp";
import notlybanner3 from "../assets/images/notlybanner3.webp";
export { notly2, notly3, notlybanner3 };

import sahnesen2 from "../assets/images/websiteImages/sahnesen2.webp";
import sahnesen3 from "../assets/images/websiteImages/sahnesen3.webp";
export { sahnesen2, sahnesen3 };
import sabirozelservis from "../assets/images/websiteImages/sabirozelservis.webp";
import sabirozelservis3 from "../assets/images/websiteImages/sabirozelservis3.webp";
export { sabirozelservis, sabirozelservis3 };
import pure from "../assets/images/websiteImages/pure.webp";
export { pure };
import pure2 from "../assets/images/websiteImages/pure2.webp";
export { pure2 };
import fgaranticard from "../assets/images/websiteImages/fgaranticard.webp";
export { fgaranticard };
import fgaranticard2 from "../assets/images/websiteImages/fgaranticard2.webp";
export { fgaranticard2 };
import poppinweb from "../assets/images/websiteImages/poppinweb.webp";
export { poppinweb };
import iphoneweb from "../assets/images/websiteImages/iphoneweb.webp";
import iphoneweb2 from "../assets/images/websiteImages/iphoneweb2.webp";
export { iphoneweb, iphoneweb2 };

export { projectbanner, blogbanner, sabiroto, poppin, garanticard };
export { kutukalan, sabirotologo };
export { sahnesen };
export { iphonechip, gray, runaley2, itstime, homework2 };
export { dockerpostman, sunucu };
export { logo, logo2, navbarlogo };
export { createMusicImg };
export { readmeImg };