import mor from "../assets/images/mor.jpeg";
import sahnesen from "../assets/images/sahnesen.png";
import abstract1 from "../assets/images/abstract1.png";
import abstract2 from "../assets/images/abstract2.png";
import iphonechip from "../assets/images/iphonechip.jpeg";
import gray from "../assets/images/gray.jpeg";
import runaley from "../assets/images/runaley.png";
import itstime from "../assets/images/itstime.jpeg";
import homework2 from "../assets/images/homework3.png";
import projectbanner from "../assets/images/projectbanner.jpeg";
import blogbanner from "../assets/images/blogbanner.jpeg";
import kutukalan from "../assets/logo/kutukalan.png";
import sabirotologo from "../assets/logo/sabirotologo.png";
import aboutImage from "../assets/images/aboutImage.png";
import dockerpostman from "../assets/images/docker&postman.png";
import sunucu from "../assets/images/sunucu.png";
import sabiroto from "../assets/images/sabiroto.png";
import poppin from "../assets/images/poppin.png";
import garanticard from "../assets/images/garanticard.png";
import logo from "../assets/logo/logo.png";
import logo2 from "../assets/logo/logo2.png";
import navbarlogo from "../assets/logo/navbarlogo.png";

export { projectbanner, blogbanner, sabiroto, poppin, garanticard };
export { kutukalan, sabirotologo, aboutImage };
export { mor, sahnesen };
export { abstract1, abstract2, iphonechip, gray, runaley, itstime, homework2 };
export { dockerpostman, sunucu };
export { logo, logo2, navbarlogo };
