name: Kutukalan Portfolio Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    if: github.repository == 'umutkutukalan/kutukalan-web'
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - run: npm ci
    
    - name: Create env file
      run: |
        echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env.production       
    - run: npm run build --if-present
    
    - name: Deploy Frontend
      run: |
          set -e
          echo "Preparing frontend directory"
          mkdir -p /opt/kutukalancom/frontend

          echo "Cleaning old build"
          rm -rf /opt/kutukalancom/frontend/*

          echo "Copying new build files"
          cp -r dist/* /opt/kutukalancom/frontend/

          echo "Deployment completed"
